version: '3.5'

services:
  hello_k8s:
    image: hello-k8s:latest
    build:
        context: .
    container_name: hello-k8s
    env_file: docker.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: hello_k8s_dev
      POSTGRES_PASSWORD: postgres